# 站点设置
title: "宸良手纪"
description: "讲述项目背后的故事 | share the stories behind the repos"
baseurl: "/blog" 
url: "https://sapchen.github.io/blog" 

# 构建设置
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# 主题设置（先使用默认主题）
theme: jekyll-theme-hacker

# 作者信息
author:
  name: "宸良手纪"
  email: "chenliang@bupt.cn"

# 社交链接
github_username: sapchen

hacker:
  skin: dark  # 推荐用dark，更有黑客风格
  title: "宸良手纪"  # 可选：覆盖主题标题
  description: "讲述项目背后的故事"  # 可选：覆盖主题描述

# 其他设置
permalink: /:year/:month/:day/:title/
timezone: Asia/Shanghai  # 设置时区

# 排除文件
exclude:
  - vendor
  - .bundle
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
  - "*.gem"
  - "*.gemspec"
  - "*.template"
  - "*.erb"
  - site_template
  - lib