# 站点设置
title: "宸良手纪"
description: "讲述项目背后的故事 | share the stories behind the repos"
baseurl: "/blog" 
url: "https://sapchen.github.io/blog" 

# 构建设置
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# 主题设置（先使用默认主题）
remote_theme: pages-themes/hacker@v0.2.0

# 作者信息
author:
  name: "_061837@bupt"
  email: "chenliang@bupt.cn"

# 社交链接
github_username: _061837@bupt

# 其他设置
permalink: /:year/:month/:day/:title/
timezone: Asia/Shanghai  # 设置时区

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md