# 站点设置
title: "宸良手纪"
description: "讲述项目背后的故事"
baseurl: "/blog"  # 如果仓库名是 blog，就保持空；如果是 用户名.github.io，就保持空
url: "https://sapchen.github.io/blog"  # 或者 "https://你的用户名.github.io/blog"

# 构建设置
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 主题设置（先使用默认主题）
theme: minima

# 作者信息
author:
  name: "_061837@bupt"
  email: "chenliang@bupt.cn"

# 社交链接
github_username: sapchen

# 其他设置
permalink: /:year/:month/:day/:title/
timezone: Asia/Shanghai  # 设置时区

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md