# 站点设置
title: "宸良手纪"
description: "讲述项目背后的故事"
baseurl: "/blog"
url: "https://sapchen.github.io/blog"

# 构建设置
markdown: kramdown
highlighter: rouge
remote_theme: pages-themes/hacker@v0.2.0

# 主题配置
hacker:
  skin: dark

# 作者信息
author:
  name: "宸良"
  email: "chenliang@bupt.cn"

github_username: sapchen

# 其他设置
permalink: /:year/:month/:day/:title/
timezone: Asia/Shanghai