# 站点设置
title: "宸良手纪"
description: "讲述项目背后的故事 | share the stories behind the repos"
baseurl: "/blog" 
url: "https://sapchen.github.io/blog" 

# 构建设置
markdown: kramdown
highlighter: rouge

# 主题设置（先使用默认主题）
theme: jekyll-theme-hacker

# 作者信息
author:
  name: "宸良手纪"
  email: "chenliang@bupt.cn"

# 社交链接
github_username: _061837@bupt

# Hacker主题特定的颜色配置（可选）
hacker:
  skin: classic  # classic 或 dark

# 其他设置
permalink: /:year/:month/:day/:title/
timezone: Asia/Shanghai  # 设置时区

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md